version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=pmn_garage
    volumes:
      - db-data:/var/lib/mysql:delegated
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci', '--max_connections=1000' ]
    ports:
      - "13306:3306"

  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"
    links:
      - mysql

volumes:
  db-data:
